### PR TITLE
Configurator

### PR DESCRIPTION
**Pull request by devilismyfriend**
Added a gui configurator.
Includes your auto settings function

### CODE REVIEW

**Comment by devilismyfriend** [comment]
Features:
-GUI should be compatible between Linux and Windows (if customtkinter is installed)
-Load a YAML config file to edit
-Relevant settings are exposed
-Auto-adjust settings based on the dataset
-Settings validation (batch size etc)
-Dataset validation (will show an error if the selected folder doesn't have expected structure)
-Will show an update button when git is updated and trigger an update

To add:
-Cloud export option with accompanying dynamic notebook
-Inference option to sample your model faster

image

**Comment by 152334H** [comment]
yo this is great

Would you like to be added as a collaborator, actually? If not, then just tell me whenever it's ready to merge

**Comment by devilismyfriend** [comment]
> yo this is great
> 
> Would you like to be added as a collaborator, actually? If not, then just tell me whenever it's ready to merge

Sure, but fyi I just nuked my environment to make sure everything is installing correctly and found out the customtkinter isn't getting installed on windows with the modification you made to the requirements file, would you mind if I change it?

**Comment by 152334H** [comment]
oh well it was supposed to be `win32` rather than windows

But if the GUI is going to work with Linux as well then there's no harm in removing the whole thing

**Comment by 152334H** [comment]
Since there's more than one maintainer now, I'm going to try to make use of pull requests more && random commits less

**Comment by 152334H** [comment]
@devilismyfriend will you be writing README instructions for the training app? If not, it'll be a bit before I can boot up windows to test it on a machine with a GPU.

also, it's a bit weird to use a new yaml library instead of the PyYAML library that is already installed and used extensively in tortoise... I understand if the yaml code you're using was lifted from elsewhere, but ideally we should avoid installing two libraries that fulfill roughly the same purpose

**Comment by devilismyfriend** [comment]
> @devilismyfriend will you be writing README instructions for the training app? If not, it'll be a bit before I can boot up windows to test it on a machine with a GPU.
> 
> also, it's a bit weird to use a new yaml library instead of the PyYAML library that is already installed and used extensively in tortoise... I understand if the yaml code you're using was lifted from elsewhere, but ideally we should avoid installing two libraries that fulfill roughly the same purpose

I tried that library first and it completely destroyed the file so I changed it, but I agree, I'd rather use it if possible.

I think I'm going to record a short video to showcase the process and help people get started

**Pull request merged**
